"""empty message

Revision ID: 055fd238f994
Revises: 1da82eb5c668
Create Date: 2022-10-10 21:24:30.828665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055fd238f994'
down_revision = '1da82eb5c668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=20), nullable=False),
    sa.Column('planet', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
