"""empty message

Revision ID: 09aeb5be2275
Revises: cfac68449575
Create Date: 2022-10-14 18:09:59.824080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09aeb5be2275'
down_revision = 'cfac68449575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###
