"""empty message

Revision ID: 1da82eb5c668
Revises: d32296efe88c
Create Date: 2022-10-07 14:31:30.003055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da82eb5c668'
down_revision = 'd32296efe88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('eye_color', sa.String(length=20), nullable=False))
    op.add_column('people', sa.Column('hair_color', sa.String(length=20), nullable=False))
    op.add_column('people', sa.Column('skin_color', sa.String(length=20), nullable=False))
    op.add_column('planets', sa.Column('orbital_period', sa.String(length=20), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'planets', ['orbital_period'])
    op.create_unique_constraint(None, 'planets', ['rotation_period'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_constraint(None, 'planets', type_='unique')
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('people', 'skin_color')
    op.drop_column('people', 'hair_color')
    op.drop_column('people', 'eye_color')
    # ### end Alembic commands ###
