"""empty message

Revision ID: 3118691f2d38
Revises: 53aa91908f99
Create Date: 2022-10-15 01:52:12.617817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3118691f2d38'
down_revision = '53aa91908f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
